server {
    listen 80;
    server_name lab071 lab071.kasetsart.university;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}
