server {
    listen 80;
    server_name lab071 lab071.kasetsart.university;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name lab071 lab071.kasetsart.university;

    ssl_certificate /etc/letsencrypt/live/lab071.kasetsart.university/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lab071.kasetsart.university/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}
